main: fr.dragorn421.witchtower.WitchTowerPlugin
name: WitchTower
version: 0.1
author: Dragorn421
commands:
  witchtower:
    usage: /witchtower <projectile | shoot | tower | witch>
    description: Main command